<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Playground" Id="{8eb2478b-dfad-4133-8e9b-5cd4ecfbbad8}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FINAL Playground EXTENDS Node
VAR
	content : _ITcVnImage;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{181531a4-5453-4c8e-8722-585931b10bf9}" />
    <Method Name="Clone" Id="{cec82d75-f155-4784-a43d-387f9ee1bdac}">
      <Declaration><![CDATA[METHOD PUBLIC Clone : I_Node
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Clone := this^;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Dispose" Id="{7708a250-3ac6-4df8-aaf2-fad4b0369d75}">
      <Declaration><![CDATA[METHOD Dispose
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{c123118c-9d74-4bb9-9311-7cac55c8109b}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddContent('content', content);]]></ST>
      </Implementation>
    </Method>
    <Property Name="Image" Id="{8e37f6d4-b014-4d52-b17a-7b02d20cbf4f}">
      <Declaration><![CDATA[PROPERTY Image : reference to _ITcVnImage]]></Declaration>
      <Get Name="Get" Id="{04c7494d-bccd-423d-896c-a2d0d415e613}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Image ref= content;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="OnExecute" Id="{68571122-a377-4d1a-96e4-62df1bbbcbe5}">
      <Declaration><![CDATA[METHOD PROTECTED OnExecute : HRESULT
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>